duplicate make two workflows does this work

diff --git a/.github/workflows/realm-update-reminder.yml b/.github/workflows/realm-update-reminder.yml
--- a/.github/workflows/realm-update-reminder.yml
+++ b/.github/workflows/realm-update-reminder.yml
@@ -77,3 +77,83 @@ jobs:
             exit 11
           fi
         shell: bash
+
+name: realm-defaultUser-reminder 
+on:
+  pull_request:
+    branches:
+      - master
+      - staging
+      - develop
+
+jobs:
+  build:
+
+    name: remind defaultUser
+
+    runs-on: ubuntu-latest
+
+    timeout-minutes: 2
+
+    steps:
+      - uses: actions/checkout@v1
+      - name: Checkout @v1
+        run: echo checked out
+      - name: Dump GitHub context
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: echo "$GITHUB_CONTEXT"
+      - name: Prepare repo
+        env:
+          GIT_MASTER_BRANCH_SHA: ${{ github.event.pull_request.base.sha }}
+          GIT_PR_BRANCHNAME: ${{ github.head_ref }}
+          GIT_DESTINATION_BRANCHNAME: ${{ github.base_ref }}
+          GIT_COMMIT_SHA: ${{ github.event.after }}
+          GIT_TOKEN: ${{ github.token }}
+        run: |
+          #echo "${GITHUB_REF:11}"
+          #echo "current commit sha: $GIT_COMMIT_SHA"
+          git checkout "$GIT_PR_BRANCHNAME"
+          git checkout "$GIT_DESTINATION_BRANCHNAME"
+          git checkout "$GIT_PR_BRANCHNAME"
+          #echo $(git branch)
+          echo "master branch base sha is $GIT_MASTER_BRANCH_SHA"
+          echo "newline to trigger the bot"
+          echo $(git log -n5 --pretty=oneline)
+      - name: Compare for higher Realm schema version
+        env:
+            GIT_PR_BRANCHNAME: ${{ github.head_ref }}
+            GIT_DESTINATION_BRANCHNAME: ${{ github.base_ref }}
+        run: |
+          echo "Check if we have modified any realm related files"
+          modifiedNames=$(git diff "$GIT_DESTINATION_BRANCHNAME" "$GIT_PR_BRANCHNAME" --name-only)
+          hasMatch=$(echo $modifiedNames | egrep '' || [[ $? == 1 ]] | echo "false")
+          hasAddedNewRealmModel=$(git diff "$GIT_DESTINATION_BRANCHNAME" "$GIT_PR_BRANCHNAME" --unified=0 -G': Object')
+          if [[ "$hasMatch" = "false" && (-z "$hasAddedNewRealmModel") ]]
+          then
+            echo "No default.realm related files have been modified or created, exiting"
+            exit 0
+          fi
+          echo "Compare for higher Realm schema version"
+          search=$(git diff "$GIT_DESTINATION_BRANCHNAME" "$GIT_PR_BRANCHNAME" --unified=0 -G'Realm.configureRealm\(schemaVersion:' learning.swift | egrep '[+-]Realm.configureRealm\(schemaVersion:' || [[ $? == 1 ]] | echo "didntModify")
+          if [[ (! -z "$search") && "$search" = "didntModify" ]]
+          then 
+            echo "Didnt update schemaVersion number at all, exiting"
+            exit 10
+          fi
+          before=$(echo $search | egrep -o [0-9]+ | head -1)
+          after=$(echo $search | egrep -o [0-9]+ | tail -1 )
+          if [[ (! -z "$search") && "$before" -lt "$after" ]]
+          then
+            echo "Good!"
+            echo "$search"
+            echo "- old version was $before"
+            echo "+ new version is  $after"
+            exit 0
+          else 
+            echo "failure"
+            echo "Empty or Invalid realm version found make sure that $before < $after"
+            echo "Instead got $search"
+            exit 11
+          fi
+        shell: bash
