moving to node

diff --git a/.github/workflows/realm-update-reminder.yml b/.github/workflows/realm-update-reminder.yml
--- a/.github/workflows/realm-update-reminder.yml
+++ b/.github/workflows/realm-update-reminder.yml
@@ -16,6 +16,7 @@ jobs:
 
     steps:
       - uses: actions/checkout@v1
+      - uses: actions/setup-node@master  # Reference a branch
       - name: Search for modified lines beginning with "print" here
         run: |
           echo Starting multiline
@@ -23,6 +24,10 @@ jobs:
           search=$(git diff --unified=0 -G'print' learning.swift)
           if [ ! -z "$search" ]; then
             echo "We modified the line in this file make sure its correct"
+            exit 0
+          else 
+            echo "failure"
+            exit 1
           fi
           echo Done!
         shell: sh
